### ISSUE TITLE
Locked down environment

### ISSUE THREAD

**Issue by Iril** [Cyanoth/Bitbucket-EagerPR-Updates#1]
Good morning, 
My workplace has a locked down environment and I am unable to add / use tools like the atlas packager. Is there any chance you can offer this as a installable app for Bitbucket ?

Many Thanks in Advance
Martin

**Comment by Cyanoth** [comment]
You can download an already packaged jar file from: https://github.com/Cyanoth/Bitbucket-EagerPR-Updates/releases, download eagerpr-0.1.5.jar 

Then on the Bitbucket Instance:
Global Admin -> Manage Apps -> Upload App and Select the downloaded jar file.
